on:
  push:
      branches:
      - master
  
jobs:
  build:
  
      runs-on: ubuntu-latest
    
      steps:
        - uses: actions/checkout@v3
        - name: Deploy with github-pages
          uses: JamesIves/github-pages-deploy-action@v4
          env:
            ACCESS_TOKEN: ${{ secrets.TOKEN }}
            BASE_BRANCH: master # The branch the action should deploy from.
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: target # The folder the action should deploy.
            BUILD_SCRIPT: npm install && npm run-script build
