name: Build and Deploy Svelte App to GitHub Pages

on:
  push:
    branches:
      - master  # You can change this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Svelte app
      run: npm run build

    - name: Archive production build
      uses: actions/upload-artifact@v2
      with:
        name: svelte-app
        path: build  # This should match the output directory of your Svelte build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: svelte-app
        path: svelte-app

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: svelte-app  # This should match the artifact path where the build is extracted
